apiVersion: v1
kind: Template
metadata:
  name: is-agent
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
     run: is-agent
    name: is-agent
  spec:
    replicas: 1
    selector:
      run: is-agent
    template:
      metadata:
        labels:
          run: is-agent
      spec:
        containers:
        - command:
          - /sag/profiles/IS_default/bin/sagis100
          - console
          image: is_agent:${IMAGE_TAG}
          name: is-agent
          ports:
          - containerPort: 5555
            protocol: TCP
          - containerPort: 9999
            protocol: TCP
        serviceAccount: "${SERVICE_ACCOUNT}"
        serviceAccountName: "${SERVICE_ACCOUNT}"
  triggers:
  - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: is-agent
    name: is-agent
  spec:
    ports:
    - name: port-1
      port: 5555
      protocol: TCP
      targetPort: 5555
    - name: port-2
      port: 9999
      protocol: TCP
      targetPort: 9999
    selector:
      run: is-agent

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      run: is-agent
    name: "${ROUTE_NAME_5555}"
  spec:
#    host: ${ROUTE_NAME_5555}.${TENANT_NAME}-${WILDCARD_DOMAIN}
    port:
      targetPort: 5555
    to:
      kind: Service
      name: is-agent
      weight: 100

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      run: is-agent
    name: "${ROUTE_NAME_9999}"
  spec:
#    host: ${ROUTE_NAME_9999}.${TENANT_NAME}-${WILDCARD_DOMAIN}
    port:
      targetPort: 9999
    to:
      kind: Service
      name: is-agent
      weight: 100

parameters:
- name: SERVICE_ACCOUNT
  description: "Service Account for higher privileges"

- name: ROUTE_NAME_5555
  description: "Name of route for port 5555"
  value: "is-agent-5555"

- name: ROUTE_NAME_9999
  description: "Name of route for port 9999"
  value: "is-agent-9999"

- name: WILDCARD_DOMAIN
  description: "Wildcard domain"
#  required: true

- name: TENANT_NAME
  description: "Tenant Name - this can be the project or namespace name"
  value: webmethods

- name: IMAGE_TAG
  description: "Tag of the container image"
  value: latest
  required: true

